### PR TITLE
Bump to TeamCity 2017.1

### PR DESCRIPTION
**Pull request by lawliet89**
https://confluence.jetbrains.com/display/TCD10/What%27s+New+in+TeamCity+2017.1

### CODE REVIEW

**Comment by sjoerdmulder** [comment]
Great thanks!

**Comment by xjewer** [comment]
@sjoerdmulder make, please, the new release version (2017.1) to build new image with this tag.

**Comment by sjoerdmulder** [comment]
@xjewer just did this. Sorry but i'm not actively working anymore with Teamcity

**Comment by xjewer** [comment]
Would you say what you are using as CI?

**Comment by sjoerdmulder** [comment]
I made the release. But I have not tested it

Op 20 apr. 2017 18:27 schreef "xjewer" <notifications@github.com>:

**Pull request merged**
