### PR TITLE
Update to 9.1.6

### PR DESCRIPTION
**Pull request by ehacke**

### CODE REVIEW

**Comment by sjoerdmulder** [comment]
Thanx, but it changes the url from http**s** to http. I would rather not do this because of possible man-in-the-middle attacks. Could you update the pull-request?

**Comment by ehacke** [comment]
@sjoerdmulder yeah I can try. The only reason I changed it was that for some reason the https endpoint for the the 9.1.6 version wasn't playing nice with the curl command and was throwing an error every time. Might have been fixed by now.

**Comment by sjoerdmulder** [comment]
A right, maybe your `java:8` is too old? Try `docker pull java:8` first

**Comment by ehacke** [comment]
@sjoerdmulder could be, I'll give it a shot.

**Comment by ehacke** [comment]
Tried pulling latest java:8, it didn't help.

I was consistently getting the error 'SSL certificate problem: unable to get local issuer certificate' using curl. 

So I switched to wget and the https endpoint works. Could be that curl uses a cacert from a different location compared to wget, I dunno.

But it works now!

**Pull request merged**
